### ISSUE TITLE
result problem

### ISSUE THREAD

**Issue by zouwenqin** [linyaog/point_based_pcgc#1]
为什么我用modelnet数据集训练的模型重构不出来原始的点云呐，这个代码确定没问题吗，我只是修改了数据集加载部分，下面是我原始输入和重构的结果

![image](https://user-images.githubusercontent.com/66156211/144801926-dc2ff1a8-c91b-4096-b1f4-6fa41e7e51c9.png)

![image](https://user-images.githubusercontent.com/66156211/144801681-b0ebd945-0b62-46ce-8d1f-49d46f640e0d.png)

**Comment by linyaog** [comment]
你好，已经有其他单位成功运行过我们的代码，并得到了和文章中相近且合理的实验结果，建议可以再检查下你修改后的代码是否哪里出现问题。感谢关注。

**Comment by zouwenqin** [comment]
好的，感谢回复。我再去试试原始的数据集和相关修改，还有请问一下能发布一下你们的原始预训练模型吗

**Comment by linyaog** [comment]
抱歉无法提供pretrained model，在此工作后我们又尝试了一些方法进行改进，因为第一次做项目没有经验，覆盖了这一版的模型，不过按照文中的设置重新训练应该是没有问题的，实验结果也不会有很大波动。

**Comment by zouwenqin** [comment]
好吧，我再去训练试试

**Comment by zouwenqin** [comment]
作者大大，还有个问题，源代码中用到的shapenet数据集是预处理过的吗，shapenet官网好像没有源代码中所用的h5格式的shapenetcorev2数据集，可否给个原始数据集的链接

**Comment by linyaog** [comment]
直接搜索shapenetcorev2即可，看来你是刚入门哈

**Comment by linyaog** [comment]
直接搜索shapenetcorev2即可，看来你是刚入门哈

**Comment by linyaog** [comment]
google搜索shapenetcorev2数据集即可

**Comment by zouwenqin** [comment]
我官网下载的shapenetcorev2数据集用这个源码无法加载诶，官网的shapenetcorev2格式是是obj文件
![image](https://user-images.githubusercontent.com/66156211/144961009-c5d38183-b7ff-4f84-b2b7-8cf674d66617.png)

**Comment by tuning12** [comment]
同样的问题 请问你解决了吗
